networks:
  default:
    driver: bridge
    name: roboshop
    #external: true #I created network already using docker network create roboshop
services:
  mongodb:
    container_name: mongodb
    build: ./mongodb
   
  catalogue:
    container_name: catalogue
    build: ./catalogue
    depends_on:
    - mongodb


  frontend:
    container_name: frontend
    build: ./frontend
    ports:
    - "80:80"
    depends_on:
    - catalogue
  
