networks:
  default:
    driver: bridge
    name: roboshop
    #external: true #I created network already using docker network create roboshop
services:
  mongodb:
    image: mongodb:v1
    container_name: mongodb
   
  catalogue:
    image: catalogue:v1
    container_name: catalogue
    depends_on:
    - mongodb


  frontend:
    image: frontend:v1
    container_name: frontend
    ports:
    - "80:80"
    depends_on:
    - catalogue
  
